---
development:
  cloud_name: shalashtein
  api_key: <%= ENV["CAPIK"] %>
  api_secret: <%= ENV["CAPIS"] %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: shalashtein
  api_key: <%= ENV["CAPIK"] %>
  api_secret: <%= ENV["CAPIS"] %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: shalashtein
  api_key: <%= ENV["CAPIK"] %>
  api_secret: <%= ENV["CAPIS"] %>
  enhance_image_tag: true
  static_file_support: false
